const PIZZAS = [
  "Margherita",
  "Marinara",
  "F""rutti di Mare",
  "Quattro Formaggi",
  "Napoletana",
  "Napoli",
  "Pugliese",
  "Montanara",
  "Emiliana",
  "Romana",
  "Fattoria",
  "Schiacciata",
  "Americana",
  "Braccio di Ferro",
  "Sarda.",
  "Tonno",
  "Valtellina",
  "Gorgonzola.",
  "Pizza al Pesto",
  "Mediterranea",
  "Ortolana",
  "Diavola",
  "Rustica",
  "Contadina",
  "Parmigiana",
  "Ricotta e Spinaci",
  "Mare e Monti",
  "Padana",
  "Tedesca",
  "Tirolese",
  "Boscaiola",
  "Vegetariana",
  "Bufalina",
  "Fontana",
  "Pizza tartufata",
  "Tricolore",
  "Caprese",
  "Fiori di zucca",
  "Funghi",
];
